name: studen_exam_poc
description: "Teknik mülakat için geliştirilmiş olan uygulama"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  #Uİ
  cupertino_icons: ^1.0.8
  google_fonts: ^6.0.2
  gap: ^3.0.1
  #BUSİNESS
  go_router: ^16.0.0
  sqflite: ^2.4.1
  path: ^1.9.1
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/student_exam_poc.db
